"use client";

import Link from "next/link";
import { Suspense, useEffect, useMemo, useState } from "react";
import { useSearchParams } from "next/navigation";
import {
  BarChart3,
  BrainCircuit,
  MessageSquareText,
  ShieldCheck,
  Swords,
  TrendingUp
} from "lucide-react";
import {
  askInteractiveAnalysis,
  compareInteractiveProperties,
  getInteractiveAnalysisOverview
} from "@/lib/api";
import { useLanguage } from "@/components/layout/LanguageProvider";
import {
  HorizontalBarList,
  MiniLineChart,
  VerticalBarChart
} from "@/components/analysis/VisualCharts";
import { Button } from "@/components/ui/Button";
import { EmptyState } from "@/components/ui/EmptyState";
import { LoadingState } from "@/components/ui/LoadingState";
import { formatCurrency } from "@/lib/utils";
import { useAuthStore } from "@/store/auth-store";

const numberFormatter = new Intl.NumberFormat("es-CR");

const businessTypeLabels = {
  sale: { es: "Venta", en: "Sale" },
  rent: { es: "Renta", en: "Rent" }
};

const propertyTypeLabels = {
  house: { es: "Casa", en: "House" },
  apartment: { es: "Apartamento", en: "Apartment" },
  condominium: { es: "Condominio", en: "Condominium" },
  lot: { es: "Lote / Terreno", en: "Lot / Land" },
  room: { es: "Habitacion", en: "Room" },
  commercial: { es: "Comercial", en: "Commercial" }
};

const formatMetricValue = (metric, side) => {
  if (!metric) return "-";

  const value = metric[`${side}Value`];
  const currency = metric[`${side}Currency`] || "USD";

  if (value === null || value === undefined) {
    return "-";
  }

  if (metric.key === "affordability") {
    return formatCurrency(value, currency);
  }

  if (metric.key === "ppsm") {
    return `${formatCurrency(value, currency)} / m2`;
  }

  if (metric.key === "size") {
    return `${numberFormatter.format(value || 0)} m2`;
  }

  if (metric.key === "services") {
    return `${numberFormatter.format(value || 0)} km`;
  }

  return numberFormatter.format(value || 0);
};

const getBusinessTypeLabel = (value, language) =>
  businessTypeLabels[value]?.[language] || value;

const getPropertyTypeLabel = (value, language) =>
  propertyTypeLabels[value]?.[language] || value;

const personaBoardLabels = {
  family: {
    es: "Zonas familiares",
    en: "Family-ready zones"
  },
  roomies: {
    es: "Zonas para roomies",
    en: "Roomies and student zones"
  },
  executive: {
    es: "Zonas ejecutivas",
    en: "Executive relocation zones"
  },
  coastal: {
    es: "Zonas costeras de inversion",
    en: "Coastal investment zones"
  }
};

function AnalysisPageContent() {
  const { language } = useLanguage();
  const { token } = useAuthStore();
  const searchParams = useSearchParams();
  const [overview, setOverview] = useState(null);
  const [comparison, setComparison] = useState(null);
  const [loadingOverview, setLoadingOverview] = useState(true);
  const [loadingComparison, setLoadingComparison] = useState(false);
  const [messages, setMessages] = useState([]);
  const [question, setQuestion] = useState("");
  const [chatLoading, setChatLoading] = useState(false);
  const [chatError, setChatError] = useState("");

  const copy = useMemo(
    () =>
      language === "en"
        ? {
            eyebrow: "Interactive Analysis",
            title: "Compare, project, and ask smarter questions before you decide.",
            description:
              "This area combines sanitized market dashboards, a two-property battle, and an AI assistant that works only with listing-level signals.",
            loadingOverview: "Loading interactive analysis...",
            loginRequired:
              "Sign in to compare favorites and chat with the analysis assistant.",
            goToFavorites: "Choose favorites to compare",
            login: "Sign in",
            summary: "Market pulse",
            forecasts: "Price projections",
            opportunities: "Opportunity zones",
            businessMix: "Inventory mix",
            compareTitle: "Property battle",
            compareDescription:
              "Use the separate Comparative Battle tab to compare two favorites with pros, cons, and an AI verdict.",
            compareEmptyTitle: "Pick two favorites to start the battle",
            compareEmptyDescription:
              "Go to Favorites, select exactly two properties, and come back here to compare them side by side.",
            compareLoading: "Running the comparison battle...",
            winner: "Recommended winner",
            tie: "Very close match",
            generatedBy: "Generated by",
            metrics: "Metric battle",
            pros: "Pros",
            cons: "Cons",
            askTitle: "DeepSeek analysis chat",
            askDescription:
              "Ask about value, zone momentum, rent flexibility, or which property fits a certain buyer profile.",
            askPlaceholder:
              "Example: Which zone has the strongest momentum for families right now?",
            askButton: "Ask the assistant",
            asking: "Thinking...",
            dashboardOnly:
              "The assistant only receives sanitized data such as price, general location, rooms, area, market score, and service-distance signals. Owner details stay out.",
            noForecasts: "No forecast data yet.",
            noOpportunities: "No opportunity zones available yet.",
            noOverview: "We could not load the interactive analysis right now.",
            activeListings: "Active listings",
            soldListings: "Sold listings",
            rentedListings: "Rented listings",
            avgPpsm: "Avg active price / m2",
            avgSaleDays: "Avg days to sell",
            currentPpsm: "Current PPSM",
            projectedPpsm: "Projected PPSM",
            closuresAndActive: "{{closed}} closings - {{active}} active",
            scoreLabel: "Score",
            demandLabel: "Demand",
            priceLabel: "Price",
            marketScoreLabel: "Market score",
            roomsBathsLabel: "Bedrooms / baths",
            tieMetric: "Tie",
            winMetric: "Win",
            loseMetric: "Lose",
            viewProperty: "View listing",
            compareInFavorites: "Open battle tab",
            aiUnavailable:
              "DeepSeek is not available right now, so responses will use internal market analysis.",
            mixedCurrencies:
              "These properties use different currencies. Monetary values are shown side by side, but price-based winners are not forced.",
            heuristic: "Heuristic",
            ai: "DeepSeek",
            compareModeTitle: "Focused property battle",
            compareModeDescription:
              "You are viewing a direct comparison between two selected favorites. This mode hides the broader market dashboard to keep the decision focused.",
            dashboardTitle: "Interactive market dashboard",
            dashboardDescription:
              "Review visual signals that buyers and renters usually care about: value per square meter, zone momentum, pet-friendly rentals, family-ready homes, and roommate supply.",
            decisionSignalsTitle: "What people usually care about",
            decisionSignalsDescription:
              "These indicators focus on real decision factors: flexible rentals, family fit, and shared-living options.",
            petFriendlyRentals: "Pet-friendly rentals",
            depositFreeRentals: "No-deposit rentals",
            furnishedRentals: "Furnished rentals",
            roommateListings: "Roommate listings",
            familyReadyListings: "Family-ready homes",
            averageArea: "Average active area",
            averageBedrooms: "Average bedrooms",
            averageBathrooms: "Average bathrooms",
            topDemandChart: "Demand by zone",
            inventoryChart: "Inventory by type",
            trendChart: "Recent PPSM trend",
            zoneMomentumTitle: "Zone momentum",
            zoneMomentumDescription:
              "Districts where closing prices are accelerating or cooling off faster.",
            personaBoardsTitle: "Best zones by buyer profile",
            personaBoardsDescription:
              "A practical lens for the needs people actually bring to the search."
          }
        : {
            eyebrow: "Analisis Interactivo",
            title: "Compara, proyecta y haz preguntas mas inteligentes antes de decidir.",
            description:
              "Este espacio mezcla dashboards sanitizados del mercado, una batalla entre dos propiedades y un asistente AI que trabaja solo con senales del inventario.",
            loadingOverview: "Cargando analisis interactivo...",
            loginRequired:
              "Inicia sesion para comparar favoritos y chatear con el asistente de analisis.",
            goToFavorites: "Elegir favoritos para comparar",
            login: "Iniciar sesion",
            summary: "Pulso del mercado",
            forecasts: "Proyecciones de precio",
            opportunities: "Zonas de oportunidad",
            businessMix: "Mezcla de inventario",
            compareTitle: "Batalla de propiedades",
            compareDescription:
              "Usa la pestaña separada de Batalla Comparativa para enfrentar dos favoritas con pros, contras y veredicto AI.",
            compareEmptyTitle: "Elige dos favoritas para iniciar la batalla",
            compareEmptyDescription:
              "Ve a Favoritos, selecciona exactamente dos propiedades y vuelve aqui para compararlas lado a lado.",
            compareLoading: "Ejecutando la batalla comparativa...",
            winner: "Ganadora recomendada",
            tie: "Empate muy cerrado",
            generatedBy: "Generado por",
            metrics: "Batalla por metricas",
            pros: "Pros",
            cons: "Contras",
            askTitle: "Chat de analisis con DeepSeek",
            askDescription:
              "Pregunta sobre valor, momentum de zona, flexibilidad de renta o que propiedad se ajusta mejor a cierto perfil.",
            askPlaceholder:
              "Ejemplo: Que zona tiene mejor momentum para familias en este momento?",
            askButton: "Preguntar al asistente",
            asking: "Pensando...",
            dashboardOnly:
              "El asistente solo recibe datos sanitizados como precio, ubicacion general, cuartos, area, market score y senales de distancias a servicios. Los datos del propietario quedan fuera.",
            noForecasts: "Aun no hay suficientes datos para proyectar.",
            noOpportunities: "Todavia no hay zonas de oportunidad calculadas.",
            noOverview: "No se pudo cargar el analisis interactivo en este momento.",
            activeListings: "Publicaciones activas",
            soldListings: "Vendidas",
            rentedListings: "Alquiladas",
            avgPpsm: "Precio activo prom. / m2",
            avgSaleDays: "Dias prom. de venta",
            currentPpsm: "PPSM actual",
            projectedPpsm: "PPSM proyectado",
            closuresAndActive: "{{closed}} cierres - {{active}} activas",
            scoreLabel: "Score",
            demandLabel: "Demanda",
            priceLabel: "Precio",
            marketScoreLabel: "Puntaje de mercado",
            roomsBathsLabel: "Cuartos / baños",
            tieMetric: "Empate",
            winMetric: "Gana",
            loseMetric: "Pierde",
            viewProperty: "Ver publicacion",
            compareInFavorites: "Abrir batalla",
            aiUnavailable:
              "DeepSeek no esta configurado en este momento, asi que las respuestas usaran heuristicas de respaldo.",
            mixedCurrencies:
              "Estas propiedades usan monedas distintas. Los valores monetarios se muestran lado a lado, pero no forzamos una ganadora solo por precio.",
            heuristic: "Heuristica",
            ai: "DeepSeek",
            compareModeTitle: "Batalla enfocada de propiedades",
            compareModeDescription:
              "Estas viendo una comparacion directa entre dos favoritas seleccionadas. Este modo oculta el dashboard amplio de mercado para mantener la decision enfocada.",
            dashboardTitle: "Dashboard interactivo de mercado",
            dashboardDescription:
              "Revisa senales visuales que la gente suele tomar en cuenta: valor por m2, momentum de zona, rentas pet-friendly, casas familiares y oferta para roomies.",
            decisionSignalsTitle: "Lo que la gente suele buscar",
            decisionSignalsDescription:
              "Estos indicadores priorizan factores reales de decision: flexibilidad de renta, ajuste familiar y opciones de vivienda compartida.",
            petFriendlyRentals: "Rentas pet-friendly",
            depositFreeRentals: "Rentas sin deposito",
            furnishedRentals: "Rentas amuebladas",
            roommateListings: "Publicaciones para roomies",
            familyReadyListings: "Casas familiares",
            averageArea: "Area activa promedio",
            averageBedrooms: "Habitaciones promedio",
            averageBathrooms: "Baños promedio",
            topDemandChart: "Demanda por zona",
            inventoryChart: "Inventario por tipo",
            trendChart: "Tendencia reciente de PPSM",
            zoneMomentumTitle: "Momentum por zona",
            zoneMomentumDescription:
              "Distritos donde los cierres se estan acelerando o enfriando mas rapido.",
            personaBoardsTitle: "Mejores zonas por perfil de cliente",
            personaBoardsDescription:
              "Una lectura practica segun necesidades reales que la gente trae al buscador."
          },
    [language]
  );

  const compareIds = useMemo(() => {
    const raw = searchParams.get("compare") || "";
    return raw
      .split(",")
      .map((item) => item.trim())
      .filter(Boolean)
      .slice(0, 2);
  }, [searchParams]);

  const isComparisonMode = compareIds.length === 2;

  useEffect(() => {
    const loadOverview = async () => {
      try {
        setLoadingOverview(true);
        const data = await getInteractiveAnalysisOverview();
        setOverview(data.analytics);
      } catch (_error) {
        setOverview(null);
      } finally {
        setLoadingOverview(false);
      }
    };

    loadOverview();
  }, []);

  useEffect(() => {
    if (compareIds.length !== 2 || !token) {
      setComparison(null);
      return;
    }

    const loadComparison = async () => {
      try {
        setLoadingComparison(true);
        const data = await compareInteractiveProperties(compareIds, language);
        setComparison(data.comparison);
      } catch (_error) {
        setComparison(null);
      } finally {
        setLoadingComparison(false);
      }
    };

    loadComparison();
  }, [compareIds, token, language]);

  const handleAsk = async () => {
    const nextQuestion = question.trim();

    if (!nextQuestion || !token) {
      return;
    }

    const nextHistory = messages
      .filter((item) => item.role === "user" || item.role === "assistant")
      .slice(-6)
      .map((item) => ({ role: item.role, content: item.content }));

    const userMessage = { role: "user", content: nextQuestion };

    setMessages((current) => [...current, userMessage]);
    setQuestion("");
    setChatLoading(true);
    setChatError("");

    try {
      const data = await askInteractiveAnalysis({
        question: userMessage.content,
        propertyIds: compareIds,
        language,
        history: nextHistory
      });

      setMessages((current) => [
        ...current,
        {
          role: "assistant",
          content: data.response.answer
        }
      ]);
    } catch (_error) {
      setChatError(
        language === "en"
          ? "The assistant could not answer right now."
          : "El asistente no pudo responder en este momento."
      );
    } finally {
      setChatLoading(false);
    }
  };

  const summaryCards = useMemo(
    () => [
      { label: copy.activeListings, value: overview?.summary?.activeListings || 0 },
      { label: copy.soldListings, value: overview?.summary?.soldListings || 0 },
      { label: copy.rentedListings, value: overview?.summary?.rentedListings || 0 },
      {
        label: copy.avgPpsm,
        value: numberFormatter.format(overview?.summary?.averageActivePpsm || 0)
      },
      {
        label: copy.avgSaleDays,
        value: numberFormatter.format(overview?.summary?.averageSaleDays || 0)
      }
    ],
    [copy, overview]
  );

  const signalBarItems = useMemo(() => {
    if (!overview?.decisionSignals) return [];

    return [
      {
        label: copy.petFriendlyRentals,
        value: overview.decisionSignals.petFriendlyRentals || 0
      },
      {
        label: copy.depositFreeRentals,
        value: overview.decisionSignals.depositFreeRentals || 0
      },
      {
        label: copy.furnishedRentals,
        value: overview.decisionSignals.furnishedRentals || 0
      },
      {
        label: copy.roommateListings,
        value: overview.decisionSignals.roommateListings || 0
      }
    ];
  }, [copy, overview]);

  const inventoryTypeBars = useMemo(
    () =>
      (overview?.businessMix?.byPropertyType || []).slice(0, 6).map((item) => ({
        label: getPropertyTypeLabel(item.propertyType, language),
        value: item.count
      })),
    [language, overview]
  );

  const opportunityBars = useMemo(
    () =>
      (overview?.opportunityZones || []).slice(0, 5).map((item) => ({
        label: item.label,
        value: item.opportunityScore,
        subtitle: `DOM ${item.averageDaysOnMarket || "-"} | PPSM ${numberFormatter.format(
          item.averagePpsm || 0
        )}`
      })),
    [overview]
  );

  const zoneMomentumBars = useMemo(
    () =>
      (overview?.zoneMomentum || []).slice(0, 5).map((item) => ({
        label: item.label,
        value: Math.abs(item.projectedDeltaPct || 0),
        subtitle: `${item.projectedDeltaPct > 0 ? "+" : ""}${item.projectedDeltaPct}% · ${
          item.currency
        } · ${item.sampleSize} ${language === "en" ? "closings" : "cierres"}`
      })),
    [language, overview]
  );

  const chatPromptSuggestions = useMemo(() => {
    const familyZone = overview?.personaBoards
      ?.find((board) => board.id === "family")
      ?.items?.[0]?.label;
    const roomiesZone = overview?.personaBoards
      ?.find((board) => board.id === "roomies")
      ?.items?.[0]?.label;
    const executiveZone = overview?.personaBoards
      ?.find((board) => board.id === "executive")
      ?.items?.[0]?.label;
    const coastalZone = overview?.personaBoards
      ?.find((board) => board.id === "coastal")
      ?.items?.[0]?.label;
    const momentumZone = overview?.zoneMomentum?.[0]?.label;

    const overviewSuggestions =
      language === "en"
        ? [
            momentumZone
              ? `Which district has the strongest momentum right now, and is ${momentumZone} still leading?`
              : "Which district has the strongest momentum right now?",
            familyZone
              ? `Why does ${familyZone} look strong for families right now?`
              : "Which district looks strongest for a family right now?",
            roomiesZone
              ? `Is ${roomiesZone} still one of the best areas for roomies or student rentals?`
              : "Where do roomies get the best balance between demand and price?",
            coastalZone
              ? `Does ${coastalZone} still look attractive for investment or is it getting expensive?`
              : "Which coastal zone looks strongest for investment right now?",
            executiveZone
              ? `Which executive relocation zone looks most stable today, and how does ${executiveZone} compare?`
              : "Which executive relocation zone looks most stable today?"
          ]
        : [
            momentumZone
              ? `Que distrito tiene el momentum mas fuerte ahora, y ${momentumZone} sigue liderando?`
              : "Que distrito tiene el momentum mas fuerte ahora?",
            familyZone
              ? `Por que ${familyZone} luce fuerte para familias en este momento?`
              : "Que distrito luce mas fuerte para una familia ahora mismo?",
            roomiesZone
              ? `Sigue ${roomiesZone} entre las mejores zonas para roomies o alquiler estudiantil?`
              : "Donde encuentran mejor balance los roomies entre demanda y precio?",
            coastalZone
              ? `Sigue ${coastalZone} atractivo para inversion o ya se esta encareciendo demasiado?`
              : "Que zona costera luce mejor para inversion en este momento?",
            executiveZone
              ? `Que zona ejecutiva luce mas estable hoy y como se compara ${executiveZone}?`
              : "Que zona ejecutiva luce mas estable hoy?"
          ];

    if (comparison?.suggestedQuestions?.length) {
      return [...new Set([...comparison.suggestedQuestions, ...overviewSuggestions])].slice(0, 5);
    }

    return overviewSuggestions.slice(0, 4);
  }, [comparison, language, overview]);

  if (loadingOverview) {
    return (
      <div className="app-shell section-pad">
        <LoadingState label={copy.loadingOverview} />
      </div>
    );
  }

  if (!overview) {
    return (
      <div className="app-shell section-pad">
        <EmptyState title={copy.noOverview} description={copy.dashboardOnly} />
      </div>
    );
  }

  return (
    <div className="app-shell section-pad space-y-8">
      <section className="surface bg-hero-grid p-8 sm:p-10">
        <span className="eyebrow">{copy.eyebrow}</span>
        <div className="mt-4 grid gap-6 lg:grid-cols-[1.1fr_0.9fr]">
          <div>
            <h1 className="max-w-4xl font-serif text-4xl font-semibold leading-tight sm:text-5xl">
              {isComparisonMode ? copy.compareModeTitle : copy.dashboardTitle}
            </h1>
            <p className="mt-4 max-w-3xl text-base leading-7 text-ink/68">
              {isComparisonMode ? copy.compareModeDescription : copy.dashboardDescription}
            </p>
          </div>
          <div className="surface border border-white/70 bg-white/70 p-5">
            <div className="flex items-center gap-3">
              <ShieldCheck className="h-5 w-5 text-pine" />
              <div className="text-sm font-semibold text-ink">{copy.dashboardOnly}</div>
            </div>
            {!overview.aiAvailable ? (
              <p className="mt-4 rounded-2xl bg-mist px-4 py-3 text-sm text-ink/70">
                {copy.aiUnavailable}
              </p>
            ) : null}
          </div>
        </div>
      </section>

      {!isComparisonMode ? (
        <>
      <section className="space-y-4">
        <div className="flex items-center gap-3">
          <BarChart3 className="h-5 w-5 text-terracotta" />
          <h2 className="text-2xl font-semibold">{copy.summary}</h2>
        </div>
        <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-5">
          {summaryCards.map((item) => (
            <div key={item.label} className="surface p-5">
              <div className="text-sm uppercase tracking-[0.18em] text-ink/40">
                {item.label}
              </div>
              <div className="mt-4 text-3xl font-semibold">{item.value}</div>
            </div>
          ))}
        </div>
      </section>

      <section className="grid gap-6 xl:grid-cols-[1.05fr_0.95fr]">
        <div className="surface p-6">
          <div className="flex items-center gap-3">
            <BrainCircuit className="h-5 w-5 text-pine" />
            <div>
              <h2 className="text-2xl font-semibold">{copy.decisionSignalsTitle}</h2>
              <p className="mt-1 text-sm text-ink/60">{copy.decisionSignalsDescription}</p>
            </div>
          </div>
          <div className="mt-5">
            <VerticalBarChart
              items={signalBarItems}
              color="#2c6847"
              valueFormatter={(value) => numberFormatter.format(value || 0)}
            />
          </div>
        </div>

        <div className="surface p-6">
          <div className="flex items-center gap-3">
            <BarChart3 className="h-5 w-5 text-lagoon" />
            <div>
              <h2 className="text-2xl font-semibold">{copy.summary}</h2>
              <p className="mt-1 text-sm text-ink/60">{copy.dashboardDescription}</p>
            </div>
          </div>
          <div className="mt-5 grid gap-3 sm:grid-cols-3">
            <div className="rounded-[24px] border border-ink/10 bg-white p-4">
              <div className="text-sm text-ink/55">{copy.averageArea}</div>
              <div className="mt-2 text-3xl font-semibold">
                {numberFormatter.format(overview.decisionSignals?.averageActiveArea || 0)} m2
              </div>
            </div>
            <div className="rounded-[24px] border border-ink/10 bg-white p-4">
              <div className="text-sm text-ink/55">{copy.averageBedrooms}</div>
              <div className="mt-2 text-3xl font-semibold">
                {overview.decisionSignals?.averageBedrooms || 0}
              </div>
            </div>
            <div className="rounded-[24px] border border-ink/10 bg-white p-4">
              <div className="text-sm text-ink/55">{copy.averageBathrooms}</div>
              <div className="mt-2 text-3xl font-semibold">
                {overview.decisionSignals?.averageBathrooms || 0}
              </div>
            </div>
          </div>
        </div>
      </section>

      <section className="grid gap-6 xl:grid-cols-[1.05fr_0.95fr]">
        <div className="surface p-6">
          <div className="flex items-center gap-3">
            <TrendingUp className="h-5 w-5 text-lagoon" />
            <h2 className="text-2xl font-semibold">{copy.forecasts}</h2>
          </div>
          {overview.forecasts?.length ? (
            <div className="mt-5 space-y-4">
              {overview.forecasts.slice(0, 4).map((item) => (
                <div
                  key={`${item.zone}-${item.currency}`}
                  className="rounded-[24px] border border-ink/10 bg-white p-4"
                >
                  <div className="flex flex-wrap items-center justify-between gap-3">
                    <div>
                      <div className="font-semibold">{item.zone}</div>
                      <div className="text-sm text-ink/55">{item.currency}</div>
                    </div>
                    <div
                      className={`rounded-full px-3 py-1 text-xs font-semibold ${
                        item.trend === "up"
                          ? "bg-pine/10 text-pine"
                          : item.trend === "down"
                            ? "bg-red-50 text-red-600"
                            : "bg-mist text-ink/70"
                      }`}
                    >
                      {item.projectedDeltaPct > 0 ? "+" : ""}
                      {item.projectedDeltaPct}%
                    </div>
                  </div>
                  <div className="mt-4 grid gap-3 sm:grid-cols-2">
                    <div className="rounded-2xl bg-mist px-4 py-3 text-sm">
                      <div className="text-ink/55">{copy.currentPpsm}</div>
                      <div className="mt-1 font-semibold">
                        {formatCurrency(item.currentAveragePpsm, item.currency)} / m2
                      </div>
                    </div>
                    <div className="rounded-2xl bg-white px-4 py-3 text-sm ring-1 ring-ink/10">
                      <div className="text-ink/55">{copy.projectedPpsm}</div>
                      <div className="mt-1 font-semibold">
                        {formatCurrency(item.projectedNextQuarterPpsm, item.currency)} / m2
                      </div>
                    </div>
                  </div>
                  <div className="mt-4">
                    <div className="mb-2 text-xs uppercase tracking-[0.18em] text-ink/45">
                      {copy.trendChart}
                    </div>
                    <MiniLineChart
                      series={item.series}
                      stroke={item.trend === "down" ? "#d9485f" : "#0b8a6a"}
                      fill={item.trend === "down" ? "rgba(217,72,95,0.12)" : "rgba(11,138,106,0.12)"}
                      emptyLabel={copy.noForecasts}
                    />
                  </div>
                </div>
              ))}
            </div>
          ) : (
            <p className="mt-5 text-sm text-ink/60">{copy.noForecasts}</p>
          )}
        </div>

        <div className="surface p-6">
          <div className="flex items-center gap-3">
            <BrainCircuit className="h-5 w-5 text-pine" />
            <div>
              <h2 className="text-2xl font-semibold">{copy.opportunities}</h2>
              <p className="mt-1 text-sm text-ink/60">{copy.topDemandChart}</p>
            </div>
          </div>
          {overview.opportunityZones?.length ? (
            <div className="mt-5">
              <HorizontalBarList
                items={opportunityBars}
                color="#2c6847"
                valueFormatter={(value) => `${numberFormatter.format(value || 0)} pts`}
              />
            </div>
          ) : (
            <p className="mt-5 text-sm text-ink/60">{copy.noOpportunities}</p>
          )}
        </div>
      </section>

      <section className="grid gap-6 xl:grid-cols-[1.05fr_0.95fr]">
        <div className="surface p-6">
          <div className="flex items-center gap-3">
            <TrendingUp className="h-5 w-5 text-terracotta" />
            <div>
              <h2 className="text-2xl font-semibold">{copy.zoneMomentumTitle}</h2>
              <p className="mt-1 text-sm text-ink/60">{copy.zoneMomentumDescription}</p>
            </div>
          </div>
          <div className="mt-5">
            <HorizontalBarList
              items={zoneMomentumBars}
              color="#e45d35"
              valueFormatter={(value) => `${Number(value || 0).toFixed(1)}%`}
            />
          </div>
        </div>

        <div className="surface p-6">
          <div className="flex items-center gap-3">
            <BrainCircuit className="h-5 w-5 text-pine" />
            <div>
              <h2 className="text-2xl font-semibold">{copy.personaBoardsTitle}</h2>
              <p className="mt-1 text-sm text-ink/60">{copy.personaBoardsDescription}</p>
            </div>
          </div>
          <div className="mt-5 grid gap-4">
            {(overview.personaBoards || []).map((board) => (
              <div key={board.id} className="rounded-[24px] border border-ink/10 bg-white p-4">
                <div className="text-lg font-semibold text-ink">
                  {personaBoardLabels[board.id]?.[language] || board.title}
                </div>
                <div className="mt-3 space-y-2">
                  {board.items.slice(0, 3).map((item) => (
                    <div
                      key={`${board.id}-${item.label}`}
                      className="flex items-center justify-between gap-3 rounded-[18px] bg-mist px-4 py-3 text-sm"
                    >
                      <div>
                        <div className="font-semibold text-ink">{item.label}</div>
                        <div className="mt-1 text-xs text-ink/55">{item.subtitle}</div>
                      </div>
                      <div className="rounded-full bg-white px-3 py-1.5 font-semibold text-pine shadow-soft">
                        {item.value}
                      </div>
                    </div>
                  ))}
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>

      <section className="surface p-6">
        <div className="flex items-center gap-3">
          <BarChart3 className="h-5 w-5 text-terracotta" />
          <div>
            <h2 className="text-2xl font-semibold">{copy.businessMix}</h2>
            <p className="mt-1 text-sm text-ink/60">{copy.inventoryChart}</p>
          </div>
        </div>
        <div className="mt-5 grid gap-6 lg:grid-cols-2">
          <div className="space-y-3">
            {(overview.businessMix?.byBusiness || []).map((item) => (
              <div key={item.businessType}>
                <div className="flex items-center justify-between text-sm">
                  <span>{getBusinessTypeLabel(item.businessType, language)}</span>
                  <span className="font-semibold">{item.count}</span>
                </div>
                <div className="mt-2 h-2 overflow-hidden rounded-full bg-mist">
                  <div
                    className="h-full rounded-full bg-lagoon"
                    style={{ width: `${Math.min(100, item.count * 4)}%` }}
                  />
                </div>
              </div>
            ))}
          </div>
          <div>
            <VerticalBarChart
              items={inventoryTypeBars}
              color="#0f4ea9"
              valueFormatter={(value) => numberFormatter.format(value || 0)}
            />
          </div>
        </div>
      </section>
        </>
      ) : null}

      <section className="surface p-6">
        <div className="flex flex-wrap items-center justify-between gap-4">
          <div>
            <div className="flex items-center gap-3">
              <Swords className="h-5 w-5 text-terracotta" />
              <h2 className="text-2xl font-semibold">{copy.compareTitle}</h2>
            </div>
            <p className="mt-2 text-sm text-ink/60">{copy.compareDescription}</p>
          </div>
          <Link href="/battle">
            <Button variant="success">{copy.compareInFavorites}</Button>
          </Link>
        </div>
      </section>

      <section className="surface p-6">
        <div className="flex items-center gap-3">
          <MessageSquareText className="h-5 w-5 text-lagoon" />
          <h2 className="text-2xl font-semibold">{copy.askTitle}</h2>
        </div>
        <p className="mt-2 text-sm text-ink/60">{copy.askDescription}</p>
        {!token ? (
          <div className="mt-5 rounded-[24px] bg-mist p-5 text-sm text-ink/70">
            {copy.loginRequired}
          </div>
        ) : (
          <>
            <div className="mt-5 space-y-4">
              {messages.length ? (
                messages.map((message, index) => (
                  <div
                    key={`${message.role}-${index}`}
                    className={`rounded-[24px] px-4 py-3 text-sm leading-7 ${
                      message.role === "assistant"
                        ? "bg-mist text-ink/75"
                        : "bg-ink text-white"
                    }`}
                  >
                    {message.content}
                  </div>
                ))
              ) : (
                <div className="rounded-[24px] bg-mist px-4 py-3 text-sm text-ink/70">
                  {chatPromptSuggestions.join(" - ") || copy.askDescription}
                </div>
              )}
            </div>

            <div className="mt-5 space-y-3">
              <textarea
                value={question}
                onChange={(event) => setQuestion(event.target.value)}
                placeholder={copy.askPlaceholder}
                className="min-h-[120px] w-full rounded-[24px] border border-ink/10 bg-white px-4 py-3 text-sm text-ink outline-none transition focus:border-lagoon"
              />
              {chatError ? <p className="text-sm text-red-600">{chatError}</p> : null}
              <div className="flex flex-wrap gap-3">
                <Button onClick={handleAsk} disabled={chatLoading || !question.trim()}>
                  {chatLoading ? copy.asking : copy.askButton}
                </Button>
                {chatPromptSuggestions.slice(0, 4).map((item) => (
                  <button
                    key={item}
                    type="button"
                    onClick={() => setQuestion(item)}
                    className="rounded-full bg-mist px-4 py-2 text-sm font-medium text-ink/75 transition hover:bg-white"
                  >
                    {item}
                  </button>
                ))}
              </div>
            </div>
          </>
        )}
      </section>
    </div>
  );
}

export default function AnalysisPage() {
  return (
    <Suspense fallback={<div className="app-shell section-pad"><LoadingState label="Cargando analisis..." /></div>}>
      <AnalysisPageContent />
    </Suspense>
  );
}
