"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { useSearchParams } from "next/navigation";
import { MessageSquareText, ShieldCheck, Swords } from "lucide-react";
import {
  askInteractiveAnalysis,
  compareInteractiveProperties
} from "@/lib/api";
import { useLanguage } from "@/components/layout/LanguageProvider";
import { Button } from "@/components/ui/Button";
import { EmptyState } from "@/components/ui/EmptyState";
import { LoadingState } from "@/components/ui/LoadingState";
import { formatCurrency } from "@/lib/utils";
import { useAuthStore } from "@/store/auth-store";

const numberFormatter = new Intl.NumberFormat("es-CR");

const formatMetricValue = (metric, side) => {
  if (!metric) return "-";

  const value = metric[`${side}Value`];
  const currency = metric[`${side}Currency`] || "USD";

  if (value === null || value === undefined) {
    return "-";
  }

  if (metric.key === "affordability") {
    return formatCurrency(value, currency);
  }

  if (metric.key === "ppsm") {
    return `${formatCurrency(value, currency)} / m2`;
  }

  if (metric.key === "size") {
    return `${numberFormatter.format(value || 0)} m2`;
  }

  if (metric.key === "services") {
    return `${numberFormatter.format(value || 0)} km`;
  }

  return numberFormatter.format(value || 0);
};

export default function BattlePage() {
  const { language } = useLanguage();
  const { token } = useAuthStore();
  const searchParams = useSearchParams();
  const [comparison, setComparison] = useState(null);
  const [loadingComparison, setLoadingComparison] = useState(false);
  const [messages, setMessages] = useState([]);
  const [question, setQuestion] = useState("");
  const [chatLoading, setChatLoading] = useState(false);
  const [chatError, setChatError] = useState("");

  const copy = useMemo(
    () =>
      language === "en"
        ? {
            eyebrow: "Comparative Battle",
            title: "Face two saved properties head to head.",
            description:
              "This workspace focuses only on the two selected properties, their trade-offs, and an AI-assisted decision summary.",
            loginRequired:
              "Sign in to open a comparative battle and chat with the assistant.",
            chooseFavorites: "Choose favorites",
            login: "Sign in",
            loading: "Running the comparative battle...",
            emptyTitle: "Pick two favorites to start",
            emptyDescription:
              "Go to Favorites, select exactly two properties, and come back here to compare them.",
            winner: "Recommended winner",
            tie: "Very close match",
            generatedBy: "Generated by",
            metrics: "Metric battle",
            pros: "Pros",
            cons: "Cons",
            askTitle: "Battle chat",
            askDescription:
              "Ask which one fits a family better, offers stronger value, or works better as an investment.",
            askPlaceholder:
              "Example: Which one gives me better long-term value?",
            askButton: "Ask the assistant",
            asking: "Thinking...",
            dashboardOnly:
              "The assistant only receives sanitized property signals such as price, general location, bedrooms, bathrooms, area, market score, and service-distance data. Owner details stay out.",
            mixedCurrencies:
              "These properties use different currencies. Monetary values are shown side by side, but price-based winners are not forced.",
            heuristic: "Heuristic",
            ai: "DeepSeek",
            viewProperty: "View listing",
            manageFavorites: "Manage favorites",
            priceLabel: "Price",
            marketScoreLabel: "Market score",
            roomsBathsLabel: "Bedrooms / baths",
            tieMetric: "Tie",
            winMetric: "Win",
            loseMetric: "Lose"
          }
        : {
            eyebrow: "Batalla Comparativa",
            title: "Enfrenta dos propiedades guardadas cara a cara.",
            description:
              "Este espacio se enfoca solo en las dos propiedades seleccionadas, sus trade-offs y un resumen de decision apoyado por AI.",
            loginRequired:
              "Inicia sesion para abrir una batalla comparativa y chatear con el asistente.",
            chooseFavorites: "Elegir favoritos",
            login: "Iniciar sesion",
            loading: "Ejecutando la batalla comparativa...",
            emptyTitle: "Elige dos favoritas para comenzar",
            emptyDescription:
              "Ve a Favoritos, selecciona exactamente dos propiedades y vuelve aqui para compararlas.",
            winner: "Ganadora recomendada",
            tie: "Empate muy cerrado",
            generatedBy: "Generado por",
            metrics: "Batalla por metricas",
            pros: "Pros",
            cons: "Contras",
            askTitle: "Chat de batalla",
            askDescription:
              "Pregunta cual se ajusta mejor a una familia, cual da mejor valor o cual funciona mejor como inversion.",
            askPlaceholder:
              "Ejemplo: Cual me da mejor valor a largo plazo?",
            askButton: "Preguntar al asistente",
            asking: "Pensando...",
            dashboardOnly:
              "El asistente solo recibe senales sanitizadas de las propiedades como precio, ubicacion general, habitaciones, baños, area, market score y distancias a servicios. Los datos del propietario quedan fuera.",
            mixedCurrencies:
              "Estas propiedades usan monedas distintas. Los valores monetarios se muestran lado a lado, pero no forzamos una ganadora solo por precio.",
            heuristic: "Heuristica",
            ai: "DeepSeek",
            viewProperty: "Ver publicacion",
            manageFavorites: "Gestionar favoritos",
            priceLabel: "Precio",
            marketScoreLabel: "Puntaje de mercado",
            roomsBathsLabel: "Cuartos / baños",
            tieMetric: "Empate",
            winMetric: "Gana",
            loseMetric: "Pierde"
          },
    [language]
  );

  const compareIds = useMemo(() => {
    const raw = searchParams.get("compare") || "";
    return raw
      .split(",")
      .map((item) => item.trim())
      .filter(Boolean)
      .slice(0, 2);
  }, [searchParams]);

  useEffect(() => {
    if (!token || compareIds.length !== 2) {
      setComparison(null);
      return;
    }

    const loadComparison = async () => {
      try {
        setLoadingComparison(true);
        const data = await compareInteractiveProperties(compareIds, language);
        setComparison(data.comparison);
      } catch (_error) {
        setComparison(null);
      } finally {
        setLoadingComparison(false);
      }
    };

    loadComparison();
  }, [compareIds, token, language]);

  const handleAsk = async () => {
    const nextQuestion = question.trim();

    if (!nextQuestion || !token || compareIds.length !== 2) {
      return;
    }

    const nextHistory = messages
      .filter((item) => item.role === "user" || item.role === "assistant")
      .slice(-6)
      .map((item) => ({ role: item.role, content: item.content }));

    const userMessage = { role: "user", content: nextQuestion };

    setMessages((current) => [...current, userMessage]);
    setQuestion("");
    setChatLoading(true);
    setChatError("");

    try {
      const data = await askInteractiveAnalysis({
        question: userMessage.content,
        propertyIds: compareIds,
        language,
        history: nextHistory
      });

      setMessages((current) => [
        ...current,
        {
          role: "assistant",
          content: data.response.answer
        }
      ]);
    } catch (_error) {
      setChatError(
        language === "en"
          ? "The assistant could not answer right now."
          : "El asistente no pudo responder en este momento."
      );
    } finally {
      setChatLoading(false);
    }
  };

  return (
    <div className="app-shell section-pad space-y-8">
      <section className="surface bg-hero-grid p-8 sm:p-10">
        <span className="eyebrow">{copy.eyebrow}</span>
        <div className="mt-4 grid gap-6 lg:grid-cols-[1.1fr_0.9fr]">
          <div>
            <h1 className="max-w-4xl font-serif text-4xl font-semibold leading-tight sm:text-5xl">
              {copy.title}
            </h1>
            <p className="mt-4 max-w-3xl text-base leading-7 text-ink/68">
              {copy.description}
            </p>
          </div>
          <div className="surface border border-white/70 bg-white/70 p-5">
            <div className="flex items-center gap-3">
              <ShieldCheck className="h-5 w-5 text-pine" />
              <div className="text-sm font-semibold text-ink">{copy.dashboardOnly}</div>
            </div>
          </div>
        </div>
      </section>

      {!token ? (
        <section className="surface p-6">
          <p className="text-sm text-ink/70">{copy.loginRequired}</p>
          <div className="mt-4 flex flex-wrap gap-3">
            <Link href="/login">
              <Button>{copy.login}</Button>
            </Link>
            <Link href="/favorites">
              <Button variant="secondary">{copy.chooseFavorites}</Button>
            </Link>
          </div>
        </section>
      ) : compareIds.length !== 2 ? (
        <EmptyState
          title={copy.emptyTitle}
          description={copy.emptyDescription}
          actionLabel={copy.chooseFavorites}
          onAction={() => {
            window.location.href = "/favorites";
          }}
        />
      ) : loadingComparison ? (
        <LoadingState label={copy.loading} />
      ) : comparison ? (
        <>
          <section className="surface p-6">
            <div className="flex flex-wrap items-center justify-between gap-4">
              <div>
                <div className="flex items-center gap-3">
                  <Swords className="h-5 w-5 text-terracotta" />
                  <h2 className="text-2xl font-semibold">{copy.winner}</h2>
                </div>
                <div className="mt-3 text-3xl font-semibold">
                  {comparison.winner === "tie"
                    ? copy.tie
                    : comparison.properties[comparison.winner === "first" ? 0 : 1]?.title}
                </div>
              </div>
              <div className="text-sm text-ink/60">
                {copy.generatedBy}:{" "}
                <span className="font-semibold">
                  {comparison.generatedBy === "deepseek" ? copy.ai : copy.heuristic}
                </span>
              </div>
            </div>

            {comparison.currencyMode === "mixed" ? (
              <div className="mt-5 rounded-[24px] border border-amber-200 bg-amber-50 px-4 py-3 text-sm text-amber-900">
                {copy.mixedCurrencies}
              </div>
            ) : null}

            <p className="mt-5 whitespace-pre-line text-sm leading-7 text-ink/70">
              {comparison.narrative}
            </p>
          </section>

          <section className="grid gap-5 xl:grid-cols-2">
            {comparison.properties.map((property) => (
              <div
                key={property._id}
                className="rounded-[28px] border border-ink/10 bg-white p-5 shadow-soft"
              >
                <div className="flex flex-wrap items-start justify-between gap-4">
                  <div>
                    <div className="text-sm uppercase tracking-[0.18em] text-terracotta">
                      {property.location.district}, {property.location.canton}
                    </div>
                    <h3 className="mt-2 text-2xl font-semibold">{property.title}</h3>
                    <div className="mt-2 text-sm text-ink/60">
                      {property.businessTypeLabel} - {property.propertyTypeLabel}
                    </div>
                  </div>
                  <Link href={`/properties/${property.slug}`}>
                    <Button variant="secondary">{copy.viewProperty}</Button>
                  </Link>
                </div>

                <div className="mt-4 grid gap-3 sm:grid-cols-2">
                    <div className="rounded-2xl bg-mist px-4 py-3">
                      <div className="text-sm text-ink/55">{copy.priceLabel}</div>
                    <div className="mt-1 font-semibold">
                      {formatCurrency(property.price, property.currency)}
                    </div>
                  </div>
                    <div className="rounded-2xl bg-mist px-4 py-3">
                      <div className="text-sm text-ink/55">{copy.marketScoreLabel}</div>
                    <div className="mt-1 font-semibold">
                      {property.analyticsSnapshot?.marketScoreLabel || "-"}
                    </div>
                  </div>
                  <div className="rounded-2xl bg-mist px-4 py-3">
                    <div className="text-sm text-ink/55">PPSM</div>
                    <div className="mt-1 font-semibold">
                      {formatCurrency(
                        property.analyticsSnapshot?.pricePerSquareMeter || 0,
                        property.currency
                      )}{" "}
                      / m2
                    </div>
                  </div>
                    <div className="rounded-2xl bg-mist px-4 py-3">
                      <div className="text-sm text-ink/55">{copy.roomsBathsLabel}</div>
                    <div className="mt-1 font-semibold">
                      {property.bedrooms} / {property.bathrooms}
                    </div>
                  </div>
                </div>

                <div className="mt-5 grid gap-4 md:grid-cols-2">
                  <div>
                    <div className="text-sm font-semibold text-pine">{copy.pros}</div>
                    <ul className="mt-3 space-y-2 text-sm text-ink/70">
                      {property.pros?.length ? (
                        property.pros.map((item) => <li key={item}>- {item}</li>)
                      ) : (
                        <li>-</li>
                      )}
                    </ul>
                  </div>
                  <div>
                    <div className="text-sm font-semibold text-terracotta">{copy.cons}</div>
                    <ul className="mt-3 space-y-2 text-sm text-ink/70">
                      {property.cons?.length ? (
                        property.cons.map((item) => <li key={item}>- {item}</li>)
                      ) : (
                        <li>-</li>
                      )}
                    </ul>
                  </div>
                </div>
              </div>
            ))}
          </section>

          <section className="surface p-6">
            <div className="flex flex-wrap items-center justify-between gap-4">
              <h2 className="text-2xl font-semibold">{copy.metrics}</h2>
              <Link href="/favorites">
                <Button variant="secondary">{copy.manageFavorites}</Button>
              </Link>
            </div>
            <div className="mt-4 space-y-3">
              {comparison.metrics.map((metric) => (
                <div
                  key={metric.key}
                  className="space-y-2 rounded-2xl bg-mist px-4 py-3 md:grid md:grid-cols-[1fr_1fr_auto_1fr] md:items-center md:gap-3 md:space-y-0"
                >
                  <div>
                    <div className="font-medium">{metric.label}</div>
                    {metric.note ? (
                      <div className="mt-1 text-xs text-ink/55">{metric.note}</div>
                    ) : null}
                  </div>
                  <div className={metric.winner === "first" ? "font-semibold text-pine" : ""}>
                    {formatMetricValue(metric, "first")}
                  </div>
                  <div className="text-center text-xs uppercase tracking-[0.18em] text-ink/45">
                    {metric.winner === "tie"
                      ? copy.tieMetric
                      : metric.winner === "first"
                        ? copy.winMetric
                        : copy.loseMetric}
                  </div>
                  <div className={metric.winner === "second" ? "font-semibold text-pine" : ""}>
                    {formatMetricValue(metric, "second")}
                  </div>
                </div>
              ))}
            </div>
          </section>

          <section className="surface p-6">
            <div className="flex items-center gap-3">
              <MessageSquareText className="h-5 w-5 text-lagoon" />
              <h2 className="text-2xl font-semibold">{copy.askTitle}</h2>
            </div>
            <p className="mt-2 text-sm text-ink/60">{copy.askDescription}</p>

            <div className="mt-5 space-y-4">
              {messages.length ? (
                messages.map((message, index) => (
                  <div
                    key={`${message.role}-${index}`}
                    className={`rounded-[24px] px-4 py-3 text-sm leading-7 ${
                      message.role === "assistant"
                        ? "bg-mist text-ink/75"
                        : "bg-ink text-white"
                    }`}
                  >
                    {message.content}
                  </div>
                ))
              ) : (
                <div className="rounded-[24px] bg-mist px-4 py-3 text-sm text-ink/70">
                  {comparison?.suggestedQuestions?.join(" - ") || copy.askDescription}
                </div>
              )}
            </div>

            <div className="mt-5 space-y-3">
              <textarea
                value={question}
                onChange={(event) => setQuestion(event.target.value)}
                placeholder={copy.askPlaceholder}
                className="min-h-[120px] w-full rounded-[24px] border border-ink/10 bg-white px-4 py-3 text-sm text-ink outline-none transition focus:border-lagoon"
              />
              {chatError ? <p className="text-sm text-red-600">{chatError}</p> : null}
              <div className="flex flex-wrap gap-3">
                <Button onClick={handleAsk} disabled={chatLoading || !question.trim()}>
                  {chatLoading ? copy.asking : copy.askButton}
                </Button>
                {comparison?.suggestedQuestions?.slice(0, 2).map((item) => (
                  <button
                    key={item}
                    type="button"
                    onClick={() => setQuestion(item)}
                    className="rounded-full bg-mist px-4 py-2 text-sm font-medium text-ink/75 transition hover:bg-white"
                  >
                    {item}
                  </button>
                ))}
              </div>
            </div>
          </section>
        </>
      ) : (
        <EmptyState
          title={copy.emptyTitle}
          description={copy.emptyDescription}
          actionLabel={copy.chooseFavorites}
          onAction={() => {
            window.location.href = "/favorites";
          }}
        />
      )}
    </div>
  );
}
